# This workflow will build the extension jar and retain the artifact.
 # For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

 name: Build jar

 on: [workflow_dispatch]

 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'adopt-hotspot'
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
     - name: Grant execute permission for OMERO server setup script
       run: chmod +x src/test/resources/omero-server/setup.sh
     - name: Grant execute permission for OMERO web setup script
       run: chmod +x src/test/resources/omero-web/setup.sh
     - name: Build with Gradle
       run: ./gradlew build -P toolchain=11
     - uses: actions/upload-artifact@v2
       with:
         name: libs
         path: build/libs
         retention-days: 1
